
[project]
name = "locomotion_evolution"
version = "1.0.0"
description = ""
dependencies = [
	"pymunk",
	"pygame",
	"pathos"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []

